### ISSUE TITLE
undefined is not an object (evaluating 'FileOpener.open')

### ISSUE THREAD

**Issue by Zianwar** [huangzuizui/react-native-file-opener#4]
Hello, is this module still working? I'm having trouble to use it.

I followed the usage on readme like this:

```javascript
var FileOpener = require('react-native-file-opener')

FileOpener
.open( 'someUrl',  'someMime',)
.then(
  () => { console.info('success!!'); }, 
  () => { console.info('error!!'); 
});
```
and I ended up with this error, as if there's nothing exported from the package: 

![](https://d17oy1vhnax1f7.cloudfront.net/items/2A0l0p2K1f0Q0Y1G1719/Screen%20Shot%202016-08-16%20at%202.18.24%20PM.png?v=4e79ebb7)

Any idea?

**Comment by huangzuizui** [comment]
i got no idea whats going on with u, u sure u have installed the module properly? cos i try it again in my new project,today, it is fine.

**Comment by Zianwar** [comment]
Hi @huangzuizui, sorry its my fault I didn't link the library properly and therefore resulting in a undefined exports.

**Comment by qbakozak** [comment]
I have the same issue with the module.

I ran 'rnpm link' command and check android/settings.gradle and android/app/build.gradle files and everything seems to be properly linked.

I'm importing the module via:
import FileOpener from 'react-native-file-opener'

Still FileOpener is being imported undefined.

**Comment by sun2rise** [comment]
@qbakozak it's the same here.. any clue?
thanks
