### ISSUE TITLE
can not open file on ios

### ISSUE THREAD

**Issue by raminious** [huangzuizui/react-native-file-opener#6]
Hi
I can't open downloaded file on iOS, but on Android is okay

device: iPhone 5 & 6 ( simulator )
iOS version: 10.0
react: 15.3.2
react-native: 0.34.1

code:

```js

const path = '/Users/ramin/Library/Developer/CoreSimulator/Devices/26051E4B-3C32-49A0-8FC9-EBCFA1C73157/data/Containers/Data/Application/F4CC8448-4115-495C-825A-00D912664820/Library/Caches/video.mp4'

// file is downloaded by react-native-fetch-blob

FileOpener.open(path, 'video/mp4')
.then((msg) => {
    console.log('success!!')
}, e => {
    console.log('error!!', e) //error!! Error: Open error(…)
})
```

**Comment by jariwalabhavesh** [comment]
#5

**Comment by markainick** [comment]
This is how I fixed it:
in XCode, in your project navigator, go to Libraries/RNFileOpener.xcodeproj/RNFileOpener/RNFileOpener.m
and change line 33:
`BOOL wasOpened = [self.FileOpener presentOpenInMenuFromRect:ctrl.view.bounds inView:ctrl.view animated:YES];`
with:
`BOOL wasOpened = [self.FileOpener presentOptionsMenuFromRect:ctrl.view.bounds inView:ctrl.view animated:YES];`

**Comment by EgaSetya** [comment]
I have the same issue. I can't open image preview on my app, I have to save the image first and open it manually on Photos.

**Comment by raminious** [comment]
@markainick  please publish new version on NPM too

**Comment by raminious** [comment]
I seems this project not maintaining. I suggest you using [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob/releases)
It supports iOS and android open file opening
https://github.com/wkh237/react-native-fetch-blob/wiki/iOS-API
