### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by dabit1** [huangzuizui/react-native-file-opener#9]
Hi!

I have an issue with your amazing tool. I'm using Android and react-native-fetch-blob to get DocumentDir path. When I save the files its destination path is the App document dir (/data/user/0/my.package/files) but tell me if I'm right, if I try to open files in this directory I'll not be able because only the app of my.package can do it. Then, how can I open my files in another app with your tool?

Many thanks and good job

**Comment by dabit1** [comment]
I fixed and pulled this!

**Comment by Mo4y** [comment]
Hi @dabit1 . I recently started using this tool but i'm stack with a simple "Error: Open error!!" since I put my files in document dir as well as you, I think maybe my problem is just like yours. so can you tell me HOW should i fix it.
so many thanks in advance.

**Comment by dabit1** [comment]
Hi @Mo4y  ! Sorry for the delay. My pull request with the fixes was merged, have you updated the library?
